package arq;


/**
* arq/SistemaArqOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from sisArq.idl
* Quinta-feira, 17 de Outubro de 2019 00h15min24s GFT
*/

public interface SistemaArqOperations 
{
  int list_Arq (String nome, String[] aq, String p);
  String[] att_clientes ();
  String[] get_Arq (int a);
  void set_Arq (String[] aq, int idd);
  String get_path (int a);
  int qtd_clientes ();
} // interface SistemaArqOperations
