package arq;


/**
* arq/trans_ArqHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from sisArq.idl
* Quinta-feira, 17 de Outubro de 2019 00h15min24s GFT
*/

abstract public class trans_ArqHelper
{
  private static String  _id = "IDL:arq/trans_Arq:1.0";

  public static void insert (org.omg.CORBA.Any a, arq.trans_Arq that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static arq.trans_Arq extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (arq.trans_ArqHelper.id (), "trans_Arq");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static arq.trans_Arq read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_trans_ArqStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, arq.trans_Arq value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static arq.trans_Arq narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof arq.trans_Arq)
      return (arq.trans_Arq)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      arq._trans_ArqStub stub = new arq._trans_ArqStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static arq.trans_Arq unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof arq.trans_Arq)
      return (arq.trans_Arq)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      arq._trans_ArqStub stub = new arq._trans_ArqStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
