package arq;


/**
* arq/trans_ArqPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from sisArq.idl
* Quinta-feira, 17 de Outubro de 2019 00h15min24s GFT
*/

public abstract class trans_ArqPOA extends org.omg.PortableServer.Servant
 implements arq.trans_ArqOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("envia_Arq", new java.lang.Integer (0));
    _methods.put ("set_clienteSA", new java.lang.Integer (1));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // arq/trans_Arq/envia_Arq
       {
         String fName = in.read_string ();
         byte $result[] = null;
         $result = this.envia_Arq (fName);
         out = $rh.createReply();
         arq.BytesHelper.write (out, $result);
         break;
       }

       case 1:  // arq/trans_Arq/set_clienteSA
       {
         String parth = in.read_string ();
         int id = in.read_long ();
         this.set_clienteSA (parth, id);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:arq/trans_Arq:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public trans_Arq _this() 
  {
    return trans_ArqHelper.narrow(
    super._this_object());
  }

  public trans_Arq _this(org.omg.CORBA.ORB orb) 
  {
    return trans_ArqHelper.narrow(
    super._this_object(orb));
  }


} // class trans_ArqPOA
