package arq;


/**
* arq/trans_ArqOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from sisArq.idl
* Quinta-feira, 17 de Outubro de 2019 00h15min24s GFT
*/

public interface trans_ArqOperations 
{
  byte[] envia_Arq (String fName);
  void set_clienteSA (String parth, int id);
} // interface trans_ArqOperations
