package arq;


/**
* arq/trans_Arq.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from sisArq.idl
* Quinta-feira, 17 de Outubro de 2019 00h15min24s GFT
*/

public interface trans_Arq extends trans_ArqOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface trans_Arq
