package arq;

/**
* arq/trans_ArqHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from sisArq.idl
* Quinta-feira, 17 de Outubro de 2019 00h15min24s GFT
*/

public final class trans_ArqHolder implements org.omg.CORBA.portable.Streamable
{
  public arq.trans_Arq value = null;

  public trans_ArqHolder ()
  {
  }

  public trans_ArqHolder (arq.trans_Arq initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = arq.trans_ArqHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    arq.trans_ArqHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return arq.trans_ArqHelper.type ();
  }

}
